### PR TITLE
New Input and removal of Samples

### PR DESCRIPTION
**Pull request by FriesischScott**
The Input has been rewritten. Instead of individual member properties per input type there is now only one property `Members` which includes all of them. The properties per type have been made `dependent` by parsing the cell array `Members`.

The `Samples` class has been removed. Mapping between the spaces has to be done at the point where it is needed through the appropriate methods, e.g. `map2physical`, `map2stdnorm`.

All algorithms in `opencossan.simulations` have been adapted and completely refactored.

Tests for the simulations and some of the optimizations are already included.

Everything that was proven to work before still works.

### CODE REVIEW

**Review by etheban — CHANGES_REQUESTED** [review]
* Tutorials Cossan Object should work. At least TutorialInput  TutorialRandomVariableSet etc... 

* I don't like instantiate an object using a static method.  

It should be possible to opencossan.common.inputs.random.LognormalRandomVariable('mean', 10e9, 'std', 1.6e9, 'description', 'Young''s modulus');
in the constructor it should not be too complicate to detect if a varargin contains mean and then call the method fromMeanAndStd

idx=find(strcmpi(varargin,'mean'));
if idx~=0
fromMeanAndStd
end

* [Idea] if we pass only the membersName can we not load them from the caller workspace?

**Comment by FriesischScott** [comment]
I will update the tutorials to make them work. But I will make the random variable changes on a different branch.

**Comment by FriesischScott** [comment]
I fixed the main tutorials and adapted them to the changes. Ignore the failing coverage check. There is some issue with codecov messing up the base coverage used for comparison.

**Comment by FriesischScott** [comment]
@etheban Did you have any chance to take another look at this?

**Comment by FriesischScott** [comment]
@etheban Any chance we can finally do this?

**Comment by etheban** [comment]
Sure. We need another 2 dedicated days.

Edo

--
Edoardo Patelli
Centre for Intelligent Infrastructure, University of Strathclyde

**Comment by teobros** [comment]
> Sure. We need another 2 dedicated days. Edo


But we discussed about this in Albarella! You were ok with this in July!

**Comment by FriesischScott** [comment]
I'm closing this because I'm annoyed that it shows up as an open PR for me in Github. The branch is still there if anyone ever needs it.

**Pull request closed without merging**
